LBHackney-IT/repairs-api-dotnet

terraform/development/main.tf
terraform/staging/main.tf

Set up Terraform for RDS resource

---

RepairsApi.Tests/Helpers/HttpClientFactoryWrapper.cs
RepairsApi.Tests/MockApiGateway.cs
RepairsApi.Tests/V1/E2ETests/PropertyApitests.cs
RepairsApi.Tests/V1/Gateways/AlertGatewayTests.cs
RepairsApi.Tests/V1/Gateways/ApiGatewayTests.cs
RepairsApi.Tests/V1/Gateways/PropertyGatewayTests.cs
RepairsApi/Startup.cs
RepairsApi/V1/Gateways/AlertsGateway.cs
RepairsApi/V1/Gateways/ApiGateway.cs
RepairsApi/V1/Gateways/HttpClientNames.cs
RepairsApi/V1/Gateways/IApiGateway.cs
RepairsApi/V1/Gateways/PropertyGateway.cs
RepairsApi/V1/Gateways/TenancyGateway.cs
RepairsApi/serverless.yml

Added named client that use aithorisation header

---

.circleci/config.yml
RepairsApi/serverless.yml

Add Security Groups to VPC config
Rename function to properly reflect project name

Fix serverless.yml

---

.circleci/config.yml
RepairsApi/Startup.cs
RepairsApi/V1/Boundary/Response/ScheduleOfRatesModel.cs
RepairsApi/V1/Controllers/ScheduleOfRatesController.cs
RepairsApi/V1/Domain/Contractor.cs
RepairsApi/V1/Domain/SORPriority.cs
RepairsApi/V1/Enums/WorkPriorityCode.cs
RepairsApi/V1/UseCase/Interfaces/IListScheduleOfRatesUseCase.cs
RepairsApi/V1/UseCase/ListScheduleOfRatesUseCase.cs

https://trello.com/c/R4Bj1aFW/279-as-a-user-i-need-to-be-able-to-select-an-sor-code-from-a-list-so-that-the-contractor-know-what-the-job-entails
Create SOR codes endpoint
Added new controller, models and usecase
Add tests, gateway implementation, EF migration for sor code Table.

Sor codes endpoint

---

RepairsApi.Tests/V1/Controllers/PropertiesControllerTests.cs
RepairsApi/Properties/launchSettings.json
RepairsApi/V1/Controllers/PropertiesController.cs

added log when requesting list

---

RepairsApi/serverless.yml

Change security group ID

---

RepairsApi/V1/Controllers/ScheduleOfRatesController.cs

update endpoint paths

---

.circleci/config.yml
Makefile

CI folder version

---

RepairsApi/V2/UseCase/ListScheduleOfRatesUseCase.cs

https://trello.com/c/R4Bj1aFW/279-as-a-user-i-need-to-be-able-to-select-an-sor-code-from-a-list-so-that-the-contractor-know-what-the-job-entails
Use correct SOR descriptions
Changed SOR  descriptions
Add Migrations

update response object

---

RepairsApi.Tests/Helpers/StubGeneration/ObjectFaker.cs
RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/Helpers/StubGeneration/RandomBoolGenerator.cs
RepairsApi.Tests/Helpers/StubGeneration/RandomDoubleGenerator.cs
RepairsApi.Tests/Helpers/StubGeneration/RandomStringGenerator.cs
RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/Gateways/WorkOrderCompletionGatewayTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/V2/Gateways/IRepairsGateway.cs

Refactored generator

---

RepairsApi.Tests/V2/UseCase/RaiseRepairUseCaseTests.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Infrastructure/Migrations/20210115125241_DateRaised.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210115125241_DateRaised.cs
RepairsApi/V2/Infrastructure/WorkOrder.cs
RepairsApi/V2/UseCase/RaiseRepairUseCase.cs

Added autopopulated date raised field

added dateraised

---

RepairsApi.Tests/InMemoryDb.cs
RepairsApi.Tests/IntegrationTests.cs
RepairsApi.Tests/V2/E2ETests/ScheduleOfRateCodesTests.cs
RepairsApi.Tests/V2/Entities/SeededDataTests.cs
RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi.Tests/V2/UseCase/ListScheduleOfRatesUseCaseTests.cs
RepairsApi/Startup.cs
RepairsApi/V2/Boundary/Response/ScheduleOfRatesModel.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Factories/DBModelFactory.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Gateways/IScheduleOfRatesGateway.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/Infrastructure/Migrations/20210118152301_SorCodeSeeding.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210118152301_SorCodeSeeding.cs
RepairsApi/V2/Infrastructure/ModelBuilderExtensions.cs
RepairsApi/V2/Infrastructure/RepairsContext.cs
RepairsApi/V2/Infrastructure/ScheduleOfRates.cs
RepairsApi/V2/SeededData/SORCodes.json
RepairsApi/V2/UseCase/Interfaces/IListScheduleOfRatesUseCase.cs
RepairsApi/V2/UseCase/ListScheduleOfRatesUseCase.cs

https://trello.com/c/R4Bj1aFW/279-as-a-user-i-need-to-be-able-to-select-an-sor-code-from-a-list-so-that-the-contractor-know-what-the-job-entails
Seeded SOR codes in the DB from a json file
Fixed the returned data structure on the SOR GET endpoint

Seed sor codes in the db

---

RepairsApi/V2/Factories/ApiToDomainFactory.cs

Removing error when no present tenancy is found

Nopresentenancy

---

RepairsApi/V2/Factories/ApiToDomainFactory.cs

change address line to use the double space split

changed address line to use double space split

---

RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/Gateways/JobStatusUpdateGatewayTests.cs
RepairsApi.Tests/V2/UseCase/UpdateJobStatusUseCaseTests.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Factories/DBModelFactory.cs
RepairsApi/V2/Gateways/IJobStatusUpdateGateway.cs
RepairsApi/V2/Gateways/IRepairsGateway.cs
RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
RepairsApi/V2/Gateways/RepairsGateway.cs
RepairsApi/V2/Infrastructure/JobStatusUpdate.cs
RepairsApi/V2/Infrastructure/RepairsContext.cs
RepairsApi/V2/UseCase/Interfaces/IUpdateJobStatusUseCase.cs
RepairsApi/V2/UseCase/UpdateJobStatusUseCase.cs

Jobstatusupdate

---

RepairsApi/V2/Factories/ResponseFactory.cs

Added sending property address when getting work orders

add getting address for work order

---

RepairsApi.Tests/V2/Controllers/Parameters/WorkOrderSearchParametersTests.cs
RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/V2/Controllers/Parameters/WorkOrderSearchParameters.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/UseCase/Interfaces/IListWorkOrdersUseCase.cs
RepairsApi/V2/UseCase/ListWorkOrdersUseCase.cs

https://trello.com/c/P2wTKLnv/324-as-a-user-i-can-view-sets-of-10-repairs-per-page-so-that-i-can-view-repairs-quickly

pagination + swagger docs

---

RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/Factories/ResponseFactory.cs

Include propertyReference in workOrder

---

RepairsApi/V2/Infrastructure/Migrations/20210120165114_PropRef.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210120165114_PropRef.cs

Added migration for property reference column

property reference migration

---

RepairsApi.Tests/V2/Factories/DBModelFactoryTests.cs
RepairsApi.Tests/V2/Factories/ResponseFactoryTests.cs
RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Infrastructure/CommunicationChannel.cs

https://trello.com/c/hDl1Z4Yc/316-as-a-repairs-hub-user-i-can-select-and-view-the-work-order-with-the-work-order-details-so-that-i-can-view-the-details-of-the-job
Added extra fields to get single work order details

Work order details

---

RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/Factories/ResponseFactory.cs

Added status

---

RepairsApi/V2/Factories/ResponseFactory.cs

null coalesce when accessing optional properties

nullable checks

---

RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/UseCase/RaiseRepairUseCaseTests.cs
RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs

https://trello.com/c/fLciBa9w/263-as-an-agent-i-can-add-multiple-sor-codes-to-a-work-order-so-that-i-can-raise-all-the-repairs-required

add validation for trade codes

---

RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/Factories/DBModelFactoryTests.cs
RepairsApi.Tests/V2/Gateways/MockRepairsGateway.cs
RepairsApi.Tests/V2/Gateways/RepairGatewayTests.cs
RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/GetWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Factories/DBModelFactory.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

Added tests to improve coverage and allow for minor refactors

Housekeeping, improving coverage and minor refactors

---

RepairsApi.Tests/Helpers/EnumerationHelper.cs
RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/E2ETests/Requests/RaiseRepair.json
RepairsApi.Tests/V2/UseCase/ListWorkOrderTasksUseCaseTest.cs
RepairsApi.Tests/V2/UseCase/RaiseRepairUseCaseTests.cs
RepairsApi/Startup.cs
RepairsApi/V2/Boundary/Response/WorkOrderItemViewModel.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Domain/Extensions.cs
RepairsApi/V2/Domain/WorkOrderTask.cs
RepairsApi/V2/Factories/DBModelFactory.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Gateways/IRepairsGateway.cs
RepairsApi/V2/Gateways/IScheduleOfRatesGateway.cs
RepairsApi/V2/Gateways/RepairsGateway.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/Infrastructure/RateScheduleItem.cs
RepairsApi/V2/Infrastructure/RepairsContext.cs
RepairsApi/V2/Infrastructure/ScheduleOfRates.cs
RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs
RepairsApi/V2/UseCase/Interfaces/IListWorkOrderTasksUseCase.cs
RepairsApi/V2/UseCase/ListWorkOrderTasksUseCase.cs

Added Extra column to listing of rate schedule items.

List wo items

---

RepairsApi.Tests/V2/Controllers/PropertiesControllerTests.cs
RepairsApi.Tests/V2/Gateways/PropertyGatewayTests.cs
RepairsApi/V2/Controllers/PropertiesController.cs
RepairsApi/V2/Gateways/PropertyGateway.cs
RepairsApi/V2/Resources.Designer.cs
RepairsApi/V2/Resources.resx

Better errors when platform api files

move to 502

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/Gateways/WorkOrderCompletionGatewayTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi/V2/Gateways/IWorkOrderCompletionGateway.cs
RepairsApi/V2/Gateways/WorkOrderCompletionGateway.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

https://trello.com/c/Rl3isVqQ/342-internal-server-error-when-completing-work-order-for-second-time
returns a 400 when trying to complete a completed order

returns 400 for alread7y completed WO

---

RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/Gateways/JobStatusUpdateGatewayTests.cs
RepairsApi.Tests/V2/Gateways/WorkOrderCompletionGatewayTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrderNotesUseCaseTests.cs
RepairsApi/Startup.cs
RepairsApi/V2/Boundary/Response/NoteListItem.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
RepairsApi/V2/Infrastructure/JobStatusUpdate.cs
RepairsApi/V2/Infrastructure/Migrations/20210205135908_AddAuthor.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210205135908_AddAuthor.cs
RepairsApi/V2/Infrastructure/RepairsContext.cs
RepairsApi/V2/Infrastructure/WorkOrder.cs
RepairsApi/V2/UseCase/Interfaces/IListWorkOrderNotesUseCase.cs
RepairsApi/V2/UseCase/ListWorkOrderNotesUseCase.cs

https://trello.com/c/Wl7RCCKc/346-as-a-user-i-can-view-a-list-of-notes-relating-to-a-work-order-so-i-can-see-the-timeline-of-communications

List notes

---

RepairsApi.Tests/V2/Gateways/JobStatusUpdateGatewayTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrderNotesUseCaseTests.cs
RepairsApi/V2/Boundary/Response/NoteListItem.cs
RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
RepairsApi/V2/Infrastructure/JobStatusUpdate.cs
RepairsApi/V2/Infrastructure/Migrations/20210208121542_AuthorEmail.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210208121542_AuthorEmail.cs
RepairsApi/V2/UseCase/ListWorkOrderNotesUseCase.cs

Add email to notes response

---

RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Infrastructure/Migrations/20210208150833_PurdyCodesSeeded.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210208150833_PurdyCodesSeeded.cs
RepairsApi/V2/Infrastructure/ModelBuilderExtensions.cs
RepairsApi/V2/Infrastructure/ScheduleOfRates.cs
RepairsApi/V2/SeededData/SORCodes.json

https://trello.com/c/Ol675XKB/347-add-x5-purdy-sors-for-testing

Added purdy codes for testing

---

RepairsApi/serverless.yml

Add SG for Production RDS instance

---

.editorconfig
RepairsApi.Tests/V2/E2ETests/ScheduleOfRateCodesTests.cs
RepairsApi/V2/Boundary/Response/LegacyScheduleOfRatesModel.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Gateways/IScheduleOfRatesGateway.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/UseCase/Interfaces/IListScheduleOfRatesUseCase.cs
RepairsApi/V2/UseCase/ListScheduleOfRatesUseCase.cs

added old route back to allow deployment

---

RepairsApi.Tests/V2/E2ETests/ScheduleOfRateCodesTests.cs
RepairsApi.Tests/V2/Gateways/SorPriorityGatewayTests.cs
RepairsApi/Startup.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Gateways/ISorPriorityGateway.cs
RepairsApi/V2/Gateways/SorPriorityGateway.cs

https://trello.com/c/0KorWkRv/370-add-priorities-endpoint

Add end point for returning priorities

---

.circleci/config.yml
RepairsApi.Tests/Helpers/StubGeneration/RandomEnumGenerator.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/V2/UseCase/ListWorkOrdersUseCase.cs

Added sort on WO endpoint to move completed to the bottom

Put completed WO at the bottom

---

RepairsApi/V2/Infrastructure/Hackney/ScheduleOfRates.cs
RepairsApi/V2/Infrastructure/Migrations/20210215093538_Appointments.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210215093538_Appointments.cs

Add migration for appointment work
Add Enabled flag on SOR table

Appointment migration

---

RepairsApi.Tests/V2/Controllers/RepairsControllerTests.cs
RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/MoreSpecificSorCodeTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrderNotesUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/UpdateJobStatusUseCaseTests.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Gateways/IRepairsGateway.cs
RepairsApi/V2/Gateways/RepairsGateway.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs
RepairsApi/V2/UseCase/Interfaces/ICompleteWorkOrderUseCase.cs
RepairsApi/V2/UseCase/Interfaces/IUpdateJobStatusUseCase.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs
RepairsApi/V2/UseCase/ListWorkOrderNotesUseCase.cs
RepairsApi/V2/UseCase/UpdateJobStatusUseCase.cs

Merge master

---

RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs

filter get contractors by contract and sor validity

add contract filters

---

RepairsApi.Tests/MockWebApplicationFactory.cs
RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/RepairsApi.csproj
RepairsApi/Startup.cs
RepairsApi/V2/Controllers/AppointmentsController.cs
RepairsApi/V2/Controllers/PropertiesController.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

ide suggestions

---

RepairsApi.Tests/V2/Gateways/SorPriorityGatewayTests.cs
RepairsApi/V2/Gateways/SorPriorityGateway.cs
RepairsApi/V2/Infrastructure/Hackney/ScheduleOfRates.cs
RepairsApi/V2/Infrastructure/Migrations/20210217121926_EnabledPriorities.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210217121926_EnabledPriorities.cs

Added days to complete and priority fields to populate from migration

Added enabled and days to priority

---

RepairsApi.Tests/V2/Gateways/WorkOrderCompletionGatewayTests.cs
RepairsApi/V2/Gateways/WorkOrderCompletionGateway.cs

Add author to notes raised through complete

Add author to notes raised through complete

---

RepairsApi.Tests/V2/Gateways/WorkOrderCompletionGatewayTests.cs
RepairsApi/V2/Gateways/WorkOrderCompletionGateway.cs

Merging master into develop to bring hotfix back

Merge master temp

---

RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/V2/Gateways/MockRepairsGateway.cs
RepairsApi.Tests/V2/UseCase/CreateWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/MoreSpecificSorCodeTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrderTasksUseCaseTest.cs
RepairsApi/V2/Boundary/Response/WorkOrderItemViewModel.cs
RepairsApi/V2/Domain/WorkOrderTask.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Infrastructure/Migrations/20210219104002_OriginalFlag.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210219104002_OriginalFlag.cs
RepairsApi/V2/Infrastructure/RateScheduleItem.cs
RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs

Add original flag to rate schedule items

Add original flag

---

RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/Factories/ResponseFactory.cs

added contrator reference to work order resposne

added contractor reference

---

RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi/Startup.cs
RepairsApi/V2/Factories/DBModelFactory.cs

Fix Contractor reference

---

RepairsApi.Tests/V2/E2ETests/ScheduleOfRateCodesTests.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Gateways/IScheduleOfRatesGateway.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/UseCase/Interfaces/IListScheduleOfRatesUseCase.cs
RepairsApi/V2/UseCase/ListScheduleOfRatesUseCase.cs

Providing a new endpoint to get a single code and by extension verify if the code is valid

Get SingleCode

---

sql/contract-migration.sql

Added sproc for migratio of data from uh

migration-sql

---

RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs

Contract should have valid date - updated test
Filter contract dates which have expired or have not started 
N/A
Returning multiple values in query recordset causing errors 
EF core query updated
N/A

modify query to filter dates

---

RepairsApi.Tests/MockWebApplicationFactory.cs
RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/E2ETests/ScheduleOfRateCodesTests.cs
RepairsApi/V2/MiddleWare/ExceptionMiddleware.cs

Refactored integration tests for readability and to adhere to AAA

Repair integration tests

---

RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/V2/Factories/ResponseFactoryTests.cs
RepairsApi.Tests/V2/Gateways/AppointmentGatewayTests.cs
RepairsApi.Tests/V2/UseCase/GetWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/MoreSpecificSorCodeTests.cs
RepairsApi.Tests/V2/UseCase/ListAppointmentsUseCaseTests.cs
RepairsApi/V2/Boundary/AppointmentResponse.cs
RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/DateConstants.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Gateways/AppointmentGateway.cs
RepairsApi/V2/Gateways/IAppointmentsGateway.cs
RepairsApi/V2/Infrastructure/AppointmentDetails.cs
RepairsApi/V2/UseCase/GetWorkOrderUseCase.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs

Adds appointment information to the work order response

Added appointment info to work order response

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/JobStatusUpdateStrategyFactoryTests.cs
RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Generated/CustomTypes/CustomJobStatusUpdates.cs
RepairsApi/V2/Infrastructure/Extensions/WorkOrderExtensions.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/JobIncompleteStrategy.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/JobStatusUpdateStrategyFactory.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/ResumeJobStrategy.cs

job status update now supported resolving job incomplete and a custom generic resume job update

Add JSU support for holding and resuming work orders

---

RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Factories/ResponseFactory.cs

Add description to list response

Add trade description

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Infrastructure/Extensions/WorkOrderExtensions.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/JobIncompleteNeedMaterialsStrategy.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/JobStatusUpdateStrategyFactory.cs

Added handling materials needed status

Added awaiting materials status

---

RepairsApi/V2/Factories/ApiToDomainFactory.cs
RepairsApi/V2/Factories/ResponseFactory.cs

Use util to cover nulls when mapping data

handle null phone number

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi/V2/Boundary/Response/WorkOrderItemViewModel.cs
RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/Domain/WorkOrderTask.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/UseCase/ListWorkOrderTasksUseCase.cs

Pass original quantity in API call

Originalquantity

---

RepairsApi.Tests/V2/E2ETests/PropertyApitests.cs
RepairsApi/V2/Controllers/PropertiesController.cs

contractor can get properties

---

RepairsApi.Tests/HttpClientExtensions.cs
RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/TestUserInformation.cs
RepairsApi.Tests/V2/Controllers/HubUserControllerTests.cs
RepairsApi.Tests/V2/E2ETests/HubUserApiTests.cs
RepairsApi.Tests/V2/Services/CurrentUserServiceTests.cs
RepairsApi/V2/Authorisation/ClaimsPrincipalExtension.cs
RepairsApi/V2/Authorisation/CurrentUserServiceExtension.cs
RepairsApi/V2/Boundary/Response/HubUserModel.cs
RepairsApi/V2/Controllers/HubUserController.cs
RepairsApi/V2/Domain/User.cs
RepairsApi/V2/Services/CurrentUserService.cs
RepairsApi/V2/Services/ICurrentUserService.cs

https://trello.com/c/8ofepMTh/21-as-a-contractor-i-am-informed-that-a-work-order-is-over-my-variation-limit-and-will-be-submitted-for-approval
See ticket
created /api/v2/hub-user end point and tests

Hub user endpoint

---

RepairsApi/serverless.yml

Update serverless.yml security group

---

.editorconfig
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi/V2/Authorisation/Groups.cs
RepairsApi/V2/Controllers/PropertiesController.cs
RepairsApi/V2/Controllers/RepairsController.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Gateways/RepairsGateway.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

https://trello.com/c/GPKJdNkN/13-as-a-contractor-i-can-see-the-status-of-a-variation-so-that-i-know-whether-to-proceed-with-the-work-or-not
Add boolean column to workorder table for variations
EF Migration
Update workorder object to return variation column in response.

Contract manager security group role

---

terraform/development/main.tf

Changed dev instance type to match the one in AWS - had to to a restore from staging which is a different instance type.

Changed dev instance type

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Boundary/WorkOrderResponse.cs
RepairsApi/V2/Factories/ResponseFactory.cs
RepairsApi/V2/Infrastructure/Extensions/WorkOrderExtensions.cs
RepairsApi/V2/Infrastructure/Migrations/20210325155133_AddReasonCodeEnumRemoveHasVariation.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210325155133_AddReasonCodeEnumRemoveHasVariation.cs
RepairsApi/V2/Infrastructure/WorkOrder.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/JobStatusUpdateStrategyFactory.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs
RepairsApi/V2/UseCase/UpdateJobStatusUseCase.cs

https://trello.com/c/GPKJdNkN/13-as-a-contractor-i-can-see-the-status-of-a-variation-so-that-i-know-whether-to-proceed-with-the-work-or-not
track on hold work order actions
Add reason code enum and column and create EF Migration
Column updates for work order actions and tests

add enum reason code column

---

RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Infrastructure/Extensions/WorkOrderExtensions.cs

Add a mapping of VariationApproved and VariationRejected
WorkStatusCode to string

Add the new work order status code

---

RepairsApi/serverless.yml

extra options

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/Services/DrsServiceTests.cs
RepairsApi.Tests/V2/UseCase/CreateWorkOrderUseCaseTests.cs
RepairsApi/V2/Exceptions/ApiException.cs
RepairsApi/V2/FeatureFlags.cs
RepairsApi/V2/Services/DrsService.cs
RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs
RepairsApi/serverless.yml

Add better error handling for DRS api
Add feature flag

Drs error handling

---

RepairsApi/RepairsApi.csproj
RepairsApi/Startup.cs
RepairsApi/serverless.yml

Configures AWS X-Ray for the API

Configure AWS XRay

---

RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/V2/Services/DrsServiceTests.cs
RepairsApi/V2/Services/DrsService.cs

Added mapping for priorities over to DRS

DRS Priority Mapping

---

RepairsApi/V2/Boundary/Response/TenureViewModel.cs
RepairsApi/V2/Factories/ResponseFactory.cs

REmvoe can raise from tenure as we use property one

---

RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs

Multiple code vary fix

---

RepairsApi/Startup.cs

+ Set ContextMissingStrategy to not cause Exceptions

Initialise XRay properly

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi.Tests/V2/Services/DrsMappingTests.cs
RepairsApi/V2/Boundary/Response/ScheduleOfRatesModel.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/Infrastructure/Hackney/ScheduleOfRates.cs
RepairsApi/V2/Infrastructure/Migrations/20210419113659_AddStandardMinuteValueColumn.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210419113659_AddStandardMinuteValueColumn.cs
RepairsApi/V2/Services/DrsMapping.cs

Add new column to db ready for the data to be migrated from UH tables
Moved E2E tests to new endpoints

Add smv to sor codes table

---

RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
RepairsApi/FilteringServiceCollectionExtensions.cs
RepairsApi/V2/Controllers/Parameters/WorkOrderSearchParameters.cs
RepairsApi/V2/Infrastructure/Extensions/HactExtensions.cs
RepairsApi/V2/Resources.Designer.cs
RepairsApi/V2/Resources.resx
RepairsApi/appsettings.json

Added priority filtering

---

RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi.Tests/V2/Services/DrsServiceTests.cs
RepairsApi/V2/Domain/Contractor.cs
RepairsApi/V2/Gateways/IScheduleOfRatesGateway.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/Infrastructure/Hackney/ScheduleOfRates.cs
RepairsApi/V2/Infrastructure/Migrations/20210422154259_ContractorDrsFilter.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210422154259_ContractorDrsFilter.cs
RepairsApi/V2/Services/DrsService.cs

Only send WorkORders for the right contractors to DRS

Only send WorkORders for the right contractors to DRS

---

RepairsApi.Tests/RepairsApi.Tests.csproj
RepairsApi.Tests/V2/Services/DrsMappingTests.cs
RepairsApi/RepairsApi.csproj
RepairsApi/V2/Services/DrsMapping.cs

convert DRS target completion dates to GMT

convert DRS target completion dates to GMT

---

RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi/V2/Notifications/DRSNotificationHandler.cs
RepairsApi/V2/Notifications/WorkOrderCancelled.cs
RepairsApi/V2/Notifications/WorkOrderCompleted.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

Work order complete notification

Work order complete notification

---

RepairsApi.Tests/Helpers/SoapMock.cs
RepairsApi.Tests/V2/E2ETests/Repairs/RepairApiTests.cs
RepairsApi.Tests/V2/E2ETests/Repairs/VariationApprovalTests.cs
RepairsApi.Tests/V2/E2ETests/Repairs/WorkOrderApprovalTests.cs
RepairsApi.Tests/V2/Notifications/DRSNotificationHandlerTests.cs
RepairsApi.Tests/V2/UseCase/CreateWorkOrderUseCaseTests.cs
RepairsApi/V2/Controllers/WorkOrdersController.cs
RepairsApi/V2/Helpers/WorkOrderExtensions.cs
RepairsApi/V2/Notifications/DRSNotificationHandler.cs
RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs
RepairsApi/appsettings.IntegrationTests.json

Fix setting of DRS flag

---

RepairsApi.Tests/V2/Services/DrsMappingTests.cs
RepairsApi/V2/Domain/Alert.cs
RepairsApi/V2/Factories/ApiToDomainFactory.cs
RepairsApi/V2/Helpers/AlertExtensions.cs
RepairsApi/V2/Services/DRS/DrsMapping.cs

Alerts are now put into the drs extended desc

Alerts in desc

---

RepairsApi.Tests/Helpers/CurrentUserServiceMock.cs
RepairsApi.Tests/Helpers/FilterConfigurationBuilder.cs
RepairsApi.Tests/Helpers/StubGeneration/ObjectGenerationExtensions.cs
RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/V2/E2ETests/Repairs/RepairApiTests.cs
RepairsApi.Tests/V2/E2ETests/Repairs/RepairFilterTests.cs
RepairsApi.Tests/V2/Filtering/WorkOrderFilterProviderTests.cs
RepairsApi.Tests/V2/UseCase/ListWorkOrdersUseCaseTests.cs
RepairsApi/FilteringServiceCollectionExtensions.cs
RepairsApi/V2/Controllers/Parameters/WorkOrderSearchParameters.cs
RepairsApi/V2/Filtering/WorkOrderFilterProvider.cs

Added filter handlers for trades and multiple contractors.
Also refactored tests for filtering

Added trade and contractor filters

---

RepairsApi.Tests/Dockerfile
RepairsApi.Tests/startup.sh

moved tests to startup shell script to get coverage on only uni tests

Code coverage

---

RepairsApi.Tests/Helpers/ControllerExtensions.cs
RepairsApi.Tests/Helpers/CurrentUserServiceMock.cs
RepairsApi.Tests/Helpers/ObjectExtensions.cs
RepairsApi.Tests/V2/Controllers/ControllerTests.cs
RepairsApi.Tests/V2/Controllers/ScheduleOfRatesControllerTests.cs
RepairsApi.Tests/V2/Gateways/RepairGatewayTests.cs
RepairsApi/V2/Authorisation/CurrentUserServiceExtension.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Gateways/RepairsGateway.cs
RepairsApi/V2/Services/CurrentUserService.cs
RepairsApi/V2/Services/ICurrentUserService.cs
run-coverage.ps1

Adding support for multiple contractors via permissions

Multi contractor

---

RepairsApi.Tests/Helpers/CurrentUserServiceMock.cs
RepairsApi.Tests/V2/Controllers/HubUserControllerTests.cs
RepairsApi/V2/Authorisation/ClaimsPrincipalExtension.cs
RepairsApi/V2/Authorisation/CurrentUserServiceExtension.cs
RepairsApi/V2/Boundary/Response/HubUserModel.cs
RepairsApi/V2/Controllers/ScheduleOfRatesController.cs
RepairsApi/V2/Services/CurrentUserService.cs

Add the users current users to the user endpoint

User contractors

---

RepairsApi.Tests/E2ETests/Repairs/RepairFilterTests.cs
RepairsApi.Tests/V2/Controllers/HubUserControllerTests.cs
RepairsApi.Tests/V2/Notifications/EmailNotificationHandlerTests.cs
RepairsApi/LambdaEntryPoint.cs
RepairsApi/Program.cs
RepairsApi/Properties/launchSettings.json
RepairsApi/RepairsApi.csproj
RepairsApi/V2/Controllers/HubUserController.cs
RepairsApi/V2/Controllers/PropertiesController.cs
RepairsApi/V2/Notifications/EmailNotificationHandler.cs
RepairsApi/V2/Services/CurrentUserService.cs
RepairsApi/V2/Services/DRS/DrsService.cs

Formatted logging

---

RepairsApi/LambdaEntryPoint.cs

DB command warning to warning level

override command logs

---

RepairsApi.Tests/E2ETests/Repairs/WorkOrderApprovalTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi/V2/Helpers/WorkOrderExtensions.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

Remove panding approval restriction for cancelling

Cancel Pending Orders

---

RepairsApi.Tests/E2ETests/Repairs/RepairApiTests.cs
RepairsApi/V2/Generated/CustomTypes/CustomJobStatusUpdates.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/JobStatusUpdateStrategyFactory.cs

Note and decimal test

---

RepairsApi.Tests/V2/Config/NotifyOptionsTests.cs
RepairsApi/V2/Email/GovUKNotifyService.cs
RepairsApi/V2/Email/NotifyOptions.cs
RepairsApi/appsettings.IntegrationTests.json
RepairsApi/serverless.yml

Cleaned up options for email templates

Dynamicoptions

---

RepairsApi/V2/Services/DRS/DrsService.cs
RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs

DRS possible timeouts cannot be diagnosed due to poor logging on the DRS Service.
Added logging.

Small: Added logging to DRS actions

---

RepairsApi/V2/Boundary/Response/PropertyResponse.cs
RepairsApi/V2/Factories/ResponseFactory.cs

Add TmoName on the Properties Response

Add TmoName on the Properties Response

---

RepairsApi.Tests/E2ETests/Repairs/DRSBackgroundServiceE2ETests.cs
RepairsApi.Tests/E2ETests/Repairs/RepairApiTests.cs
RepairsApi.Tests/MockWebApplicationFactory.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/AssignOperativesUseCaseTests.cs
RepairsApi/V2/Infrastructure/WorkOrder.cs
RepairsApi/V2/Resources.Designer.cs
RepairsApi/V2/Resources.resx
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/AssignOperativesUseCase.cs

Limits operative assignment functionality to contractors marked with the external scheduler flag

Assign operatives

---

RepairsApi.Tests/MockWebApplicationFactory.cs
RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/V2/Gateways/OperativeGatewayTests.cs
RepairsApi.Tests/V2/Services/DRS/BackgroundService/DrsBackgroundServiceTests.cs
RepairsApi.Tests/V2/Services/DRS/DrsMappingTests.cs
RepairsApi.Tests/V2/Services/DRS/DrsServiceTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/AssignOperativesUseCaseTests.cs
RepairsApi/V2/Gateways/IOperativesGateway.cs
RepairsApi/V2/Gateways/OperativesGateway.cs
RepairsApi/V2/Services/DRS/BackgroundService/DrsBackgroundService.cs
RepairsApi/V2/Services/DRS/DrsMapping.cs
RepairsApi/V2/Services/DRS/DrsService.cs
RepairsApi/V2/Services/DRS/IDrsService.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/AssignOperativesUseCase.cs

Removed code I suspect was accidentally committed which added cautionary alerts to the order comments field, meaning that iof the user maxed out the comments field it would fail to create the order in DRS

Assign drs operative

---

RepairsApi.Tests/E2ETests/Repairs/RepairApiTests.cs
RepairsApi.Tests/V2/Notifications/DRSNotificationHandlerTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi/V2/Notifications/DRSNotificationHandler.cs
RepairsApi/V2/Notifications/WorkOrderCompleted.cs
RepairsApi/V2/Notifications/WorkOrderNoAccess.cs
RepairsApi/V2/Resources.Designer.cs
RepairsApi/V2/Resources.resx
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

Added new Comment prefixes for completions and forwarding No access to DRS

Complete prefix and Drs cancel

---

RepairsApi/V2/Controllers/OperativesController.cs

Allow contract manager to use the get and list endpoints for operatives

add contract managers to read operatives

---

RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
RepairsApi/V2/Infrastructure/Extensions/WorkOrderExtensions.cs

https://www.pivotaltracker.com/story/show/178315029
Mapping No Access, to display string

Mapping No Access, to display string

---

RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs

https://www.pivotaltracker.com/n/projects/2500129/stories/178452069
Trades should be listed in alphabetical order
Trades are ordered by alphabetical order

added line to sort trades alphabetically by name

---

RepairsApi.Tests/V2/Services/DRS/DrsMappingTests.cs
RepairsApi/V2/Services/DRS/DrsMapping.cs

https://www.pivotaltracker.com/story/show/178640055

allow multiple sor codes to be sent to drs

---

RepairsApi.Tests/V2/Services/DRS/BackgroundService/DrsBackgroundServiceTests.cs
RepairsApi/V2/Infrastructure/JobStatusUpdate.cs
RepairsApi/V2/Infrastructure/RepairsContext.cs
RepairsApi/V2/Services/DRS/BackgroundService/DrsBackgroundService.cs

https://www.pivotaltracker.com/story/show/178480897

Add note to WO when drs update received

---

RepairsApi.Tests/E2ETests/Repairs/RepairApiTests.cs
RepairsApi.Tests/TestDataSeeder.cs
RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/AssignOperativesUseCaseTests.cs
RepairsApi/V2/Domain/Contractor.cs
RepairsApi/V2/Gateways/ScheduleOfRatesGateway.cs
RepairsApi/V2/Helpers/WorkOrderExtensions.cs
RepairsApi/V2/Infrastructure/Hackney/ScheduleOfRates.cs
RepairsApi/V2/Infrastructure/Migrations/20210701105639_AssignOpFlag.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210701105639_AssignOpFlag.cs
RepairsApi/V2/Infrastructure/RepairsContext.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs
RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/AssignOperativesUseCase.cs

Added a new flag so operative assignment can be set independently from external DRS integration

Added assign operative flag

---

RepairsApi/V2/UseCase/CreateWorkOrderUseCase.cs

making handling the token from DRS deal with nulls in the case of a high cost raise

handle null notification for high cost orders

---

RepairsApi.Tests/E2ETests/Repairs/RepairApiTests.cs
RepairsApi.Tests/V2/UseCase/CompleteWorkOrderUseCaseTests.cs
RepairsApi/V2/Factories/DBModelFactory.cs
RepairsApi/V2/Generated/WorkOrderComplete-M3SoR-v7-deduplicated.cs
RepairsApi/V2/Infrastructure/Migrations/20210715112203_ClosedDateAudit.Designer.cs
RepairsApi/V2/Infrastructure/Migrations/20210715112203_ClosedDateAudit.cs
RepairsApi/V2/Infrastructure/WorkOrderComplete.cs
RepairsApi/V2/UseCase/CompleteWorkOrderUseCase.cs

Adds an optional closed date to CompleteWorkOrder that will be used wo update the closed time on the work order so that it can be seperate the the event time that will appear on the note

Added closed date to work order complete
